# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1b16ba82269b8c42ada860ba751c2acd67eed8eaa80e2d3fcf36874c5b1b4525d15a98b60b8aaddca85668e34b33c07397d2342be91afc23e419f38279f79b8

test:
  secret_key_base: c966b96c0251ed22b4c3f27bf433d5a25973053c5ec1758753b767276c445e4dd2afd503ad226ee2f80e782d3db110c0c13d488d89c5bd3707e81b4aa7154aaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
